### ISSUE TITLE
"Scheduled Post" feature misses french translation for its messages

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#108]
When deleting a scheduled post the validation prompt is inconsistent.
At least in french...

![mangane-ui-2](https://user-images.githubusercontent.com/365281/208730748-220f69d0-473f-4159-bb12-e6f00b079ba5.png)

**Comment by Dehelssey** [comment]
Proposed translation : 

## Supprimer la publication planifiée
Êtes-vous sûr·e de vouloir supprimer cette publication planifiée ? Son contenu sera perdu.

Annuler / Confirmer

btw, nothing about scheduled post is translated so far, i'll rename that issue to match all missing translations.

**Comment by Dehelssey** [comment]
## tooltip when writing a post
<img width="180" alt="image" src="https://user-images.githubusercontent.com/20315413/208960435-bfdaa2f1-af98-4b05-b09b-b3bc2bfc2f00.png">
→ Planifier une publication

## modal windows of scheduled post
![image](https://user-images.githubusercontent.com/20315413/208961431-93592fad-48b8-48a0-a170-3c88cc56f447.png)
→ Planifier la publication au...
button : "Planifier"

We should also switch calendar in French and time in 24h like asked in #104 

## modale when writing a new post when some posts are already scheduled
![image](https://user-images.githubusercontent.com/20315413/208961911-82ee9aca-bdf0-47b7-8fe5-5dfe55aae7bf.png)
→ Vous avez une ou plusieurs publications planifiée. Cliquez ici pour la ou les éditer.
