### ISSUE TITLE
Reworking README file

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#113]
I’m reworking the README file for my use.

- Presentation of Mangane on top 
- References to Pleroma/Akkoma
- Wording for install instruction
- References to Soapbox
- Completed License en credits

Todo
- Reduce space between screenshots
- Update Admin FE screenshots
- Wording for activation section
- Verify and correct some external links

You can see the result here
https://github.com/bugsysop/Mangane/blob/update-doc-1/README.md

Are you interested by a push to upstream?

**Comment by Dehelssey** [comment]
Seems quite OK to me. I was already planning on new screens when new home UI is deployed !
