### ISSUE TITLE
Missing data export UI

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#118]
There is an UI fort data import but strangely not for data export...

This option is present in Akkoma FE (I don't remember for Pleroma FE, but I presume)

![akkoma-import-export](https://user-images.githubusercontent.com/365281/209458401-f764d6f8-dda3-4e18-bf51-4c48da6c5311.png)

**Comment by Cl0v1s** [comment]
Indeed I dont know where thoses features are on the interface... Do you know that @Dehelssey ?

**Comment by bugsysop** [comment]
In Akkima FE this is at the same place than the import, in settings pannel

**Comment by bugsysop** [comment]
In Mangane the URL is:

`instance.tld/settings/import`

**Comment by Cl0v1s** [comment]
Fixed in the last release !
