### ISSUE TITLE
Feature request - do not display Registration closed message when using third party authentication

### ISSUE THREAD

**Issue by muppeth** [BDX-town/Mangane#124]
In scenario when eg. LDAP authentication is used, Mangane should not display Registration Closed message.

**Comment by Cl0v1s** [comment]
Indeed !

**Comment by muppeth** [comment]
I have an idea so will try to test and contribute a possible fix for it after new years.

30 Dec 2022 01:30:49 Clovis ***@***.***>:

**Comment by Cl0v1s** [comment]
Oh great ! :D

**Comment by muppeth** [comment]
Just pushed #143 Hope it's sufficient.

**Comment by Cl0v1s** [comment]
Thanks a lot ! It will be merged in next release !
