### ISSUE TITLE
Add the option to see both Bubble and Fediverse timelines

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#132]
Bubble is a nice addition but it shares a common URL with Fediverse TL, if we select one in our settings we can see the other anywhere on Mangane.

I think the solution originally provided by @Cl0v1s in https://github.com/BDX-town/Mangane/issues/93#issuecomment-1365284583 would be a great answer IMO :

Desktop: 
<img width="1434" alt="Capture d’écran 2022-12-26 à 17 55 42" src="https://user-images.githubusercontent.com/917518/209569574-c82af5b8-7e9e-46cd-af0b-91f4795e739f.png">

Mobile:
<img width="360" alt="Capture d’écran 2022-12-26 à 17 56 18" src="https://user-images.githubusercontent.com/917518/209569579-f08988ca-adbd-45ab-af85-d4b880aeec87.png">

This way we do not complexify the overall navigation, and we keep our current logic: the "discover" section is there to help discover new people, just has the whole bubble feature.

In french "Bubble" could be replaced by "Communauté" or "Voisins"

**Comment by Cl0v1s** [comment]
I think that if we build this https://github.com/BDX-town/Mangane/issues/94
We can keep both timeline separated

**Comment by Dehelssey** [comment]
Awesome. Just wanted to be sure we wouldn't lost this in the process
