### ISSUE TITLE
Add ability to follow a post

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#133]
On Misskey you can "watch" a post to get notified when people answer to it even though you're not tagged in it. 

It can be really useful if someone asks an interesting question you also have and you wish to read the answers provided to them without needing to go and check the post once in a while. The option is in a submenu displayed when clicking the "…" icon underneath a post 

<img width="195" alt="image" src="https://user-images.githubusercontent.com/20315413/210392980-b57271a6-6ceb-4bd7-84e4-7d8359303c74.png">

**Comment by Cl0v1s** [comment]
It need to be implemented by backend. Not a frontend feature :)

**Comment by Dehelssey** [comment]
Oops, it might already be an issue in our Akkoma fork repo then >_<

Still needs a UI element to trigger the feature tho^^

**Comment by Cl0v1s** [comment]
I don't plan on actively developing our Akkoma version, it's already a fork of a fork and Akkoma has a fast enough developing cycle imo

I'll close this issue for now, maybe you should propose it on akkoma.dev ?

**Comment by Dehelssey** [comment]
Gotcha ! I'll ask them 🤞
