### ISSUE TITLE
Mastodon Support?

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#135]
More a _question_ than an issue.

Did somebody use, or tested, Mangane with Mastodon?

Working on cleaning the content of `docs/` directory, I want to know if we must maintain the SB references to Mastodon compatibility...

**Comment by Cl0v1s** [comment]
Since we are based on Soapbox 2.X it seems Mastodon support was not something they cared about. 
I've never tested it myself tho, but we don't explictly maintain it

**Comment by bugsysop** [comment]
Thanks! I will adapt the README to clarify this
