### ISSUE TITLE
Post translation and timeline "authentification" problem

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#139]
When I try to use the post translation function (in single post view) I have the error message:

```
Paramètres d'authentification invalides.
```

Tested un BDX-town as external visitor.

**Comment by bugsysop** [comment]
In fact _same error message_ when I want to go the the global timeline. E.g:
https://bdx.town/timeline/fediverse

**Comment by Dehelssey** [comment]
I don't have any error of that type with translation, nor with federated timeline.

Didn't you revoked some of your sessions ? I stumble upon this message when i accidentaly revoke current session^^ app stays loaded, i can click on some links but then i get more and more auth errors. 

If i clean refresh the tab, i have to log in again and everything's fine.

It also happens sometimes when my tab is still open on an older version of Mangane, i have to clean refresh it as well.

Let me know if that worked for you !

**Comment by Cl0v1s** [comment]
I think OP is saying that, while unauthentificated the translation function is deactivated by Akkoma, but we still she the translate button. 

We could hide that button for unauth users :)

**Comment by Cl0v1s** [comment]
Nope I think it's because if checking user settings in it, and we can not retrieve em since there is no user when unauth
