### ISSUE TITLE
Disable bubble by default

### ISSUE THREAD

**Issue by muppeth** [BDX-town/Mangane#142]
Is there a way to disable bubble feature as a default?

**Comment by Cl0v1s** [comment]
Nope, but anyway the overall nav will be reworked

**Comment by Cl0v1s** [comment]
Here https://github.com/BDX-town/Mangane/issues/94

**Comment by muppeth** [comment]
I figured. For now I changed it to be disabled by default on my fork, but perhaps it would be good to let admins decide, specially if they dont use Bubble timeline the experience is broken. Do you think it's worth it? I could push suggested fix.

**Comment by Cl0v1s** [comment]
I'm interested in your fix, I was overwhelmed by issues. I have to learn to focus on what I want to propose to users instead of trying to add every akkoma features :)

**Comment by muppeth** [comment]
As I was starting to work on the fix I realized that all Defaults can be overwritten in json file and so to disable bubble by default for all users:
```
"defaultSettings": {
    "public": {
       "bubble": false
     }
 },
```
Should this setting then be added to example file (and set to either true or false depending what you guys prefer to provide) or should this info be added into the docs file?

**Comment by Cl0v1s** [comment]
The overall navigation was modified and that particular setting, removed
