### ISSUE TITLE
Improve the profile directory 

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#15]
Voir début de la conversation https://github.com/Cl0v1s/mangane/issues/2

**Comment by Dehelssey** [comment]
je te retrouve le Xd voire j'essaie de basculer le doc de travail sur figma pour plus de praticité ?

j'en profiterai pour mettre à jour avec la nouvelle UI de Mangane !

**Comment by Dehelssey** [comment]
je t'ai envoyé le lien pour le document Figma :+1: 

[voir le proto](https://www.figma.com/proto/lOmoWp7cuw14qYPvZuoCFs/BDX.town---Design?node-id=3%3A1023&viewport=241%2C48%2C0.34&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=3%3A1023)

**Comment by Cl0v1s** [comment]
Super merci bcp !

**Comment by Dehelssey** [comment]
sachant que ça va ptet demander une nouvelle retouche graphique avec la prochaine maj....?
