### ISSUE TITLE
Rework Timeline pin 

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#153]
Some users are using the timeline pin feature on the discover timeline. 
Re-enabled it and rework the previously bad UI.

https://bdx.town/@Guerin/posts/ARVASqAp38rcRoHAyO

**Comment by Cl0v1s** [comment]
UI was removed here since it was ugly and not clear at all

https://github.com/BDX-town/Mangane/pull/145

**Comment by Dehelssey** [comment]
i didn't even see the previous UI.

For the record, right now things look like this : 
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/20315413/212016395-12a3df8f-4ca5-4bea-89ad-abdb1da8987e.png">

It only appears when you clicked on the instance favicon of a user's post (or manually typed the URL `https://bdx.town/timeline/INSTANCE_NAME.domain-name`)

On the right panel you have the name of displayed instance and a pin next to it.

You can only pin one instance timeline (hence the label "pipou.academy" on my screenshot) but the pin icon is still there and nothing tells you it's useless^^

i'll try and find some time soon to design a proposition  @Cl0v1s !

**Comment by Dehelssey** [comment]
@Cl0v1s i tried to keep it simple so there it is : 
![Pin external local timeline](https://user-images.githubusercontent.com/20315413/214175507-13716df5-418d-4694-b671-ce735660ef10.png)
