### ISSUE TITLE
Polls display wrong numbers

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#154]
Results of polls are somehow broken, numbers are like 2000% 

![image](https://user-images.githubusercontent.com/20315413/212015421-2f93e131-1142-442d-9a5a-2e62b9a64dae.png)

Like [stated by Thomas](https://social.meyer-guillot.fr/objects/1b70eed1-0ebf-45ae-8ef9-0bdc33d02616) it might be a problem with how mangane (or akkoma ?) calculates percentages ?

**Comment by Cl0v1s** [comment]
I don't think it's a backend issue, it looks like a dumb calculation error
