### ISSUE TITLE
Change default icon on install

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#158]
Right now the default favicon / local timeline icon is still soapbox's logo. 

Either we create a Mangane icon (cf #48) or at least we should display another svg icon

for example : 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/20315413/212129624-fbe080b3-064b-4fe2-a27f-675e90065017.png">
`<svg class="h-5 w-5 text-gray-600 dark:text-gray-500 group-hover:text-primary-500 dark:group-hover:text-primary-400" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" data-testid="svg-icon"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M5.931 6.936l1.275 4.249m5.607 5.609l4.251 1.275"></path><path d="M11.683 12.317l5.759 -5.759"></path><circle cx="5.5" cy="5.5" r="1.5"></circle><circle cx="18.5" cy="5.5" r="1.5"></circle><circle cx="18.5" cy="18.5" r="1.5"></circle><circle cx="8.5" cy="15.5" r="4.5"></circle></svg>`

this icon seems relevant to me, since the big circle can be seen as the instance and the smaller ones as the users from that instance. so Local.

Could that icon be used as favicon tho ? 🤔

**Comment by Cl0v1s** [comment]
I think it's indeed relevant as an Icon
