### ISSUE TITLE
No placeholder when there is no profile header image

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#165]
Context: 
- Mangane nomadic-hermit-crab-1a2609c
- Akkoma 3.5.0-0-gd9508474b

![Screenshot 2023-01-16 at 02-05-59 @aris@tmprs ynh fr My_akkoma](https://user-images.githubusercontent.com/365281/212628337-5ca7eafa-64ed-489a-8de6-f4e404fd00cd.png)

**Comment by bugsysop** [comment]
Thank !
Thing to add somewhere in documentation...

**Comment by Cl0v1s** [comment]
I'm always a bit puzzled when it comes to that sort of settings since it's more akkoma / pleroma related, but impacts the frontend as well...
