### ISSUE TITLE
Ghost message after scheduled post

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#166]
Context:

- Mangane nomadic-hermit-crab-1a2609c
- Akkoma 3.5.0-0-gd9508474b

![Screenshot 2023-01-16 at 02-56-21 Publications planifiées My_akkoma](https://user-images.githubusercontent.com/365281/212628561-fe97755f-e424-43df-b49c-6809692b1ced.png)

**Comment by Cl0v1s** [comment]
Hi, just to be sure, do you have indeed some scheduled message or no ?

**Comment by bugsysop** [comment]
Yes! And it was successfully published...

The screencap it’s from when I tried, a few minutes later, to post a « normal » status

**Comment by Cl0v1s** [comment]
Ok thanks, probably a design issue:

* Mangane schedule the post and add the post to its scheduled post list
* Akkoma publish it 
* Mangane wasnt informed by Akkoma that the scheduled post list has changed

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/282
