### ISSUE TITLE
Wrong link on instance icon

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#167]
When you click on an instance icon (just after user name) on status view you have an error page...

Context:

- Mangane nomadic-hermit-crab-1a2609c
- Akkoma 3.5.0-0-gd9508474b

![Screenshot 2023-01-16 at 10-05-07 My_akkoma](https://user-images.githubusercontent.com/365281/212640663-812f28c8-5e29-49f1-8e83-43d46c648d7d.png)

**Comment by Cl0v1s** [comment]
Duplicate https://github.com/BDX-town/Mangane/issues/129

Fixed in https://github.com/BDX-town/Mangane/releases/tag/wrestling-red-panda
