### ISSUE TITLE
Option to specify posts language

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#171]
I've been told that my posts were marked as "english" even tho most of them are french.

On Mastodon you can state a default language for your posts. 
You can also change it when writing a new one 
![image](https://user-images.githubusercontent.com/20315413/213651787-0a143df5-9296-46ef-964e-614ce9e9c9e4.png)

I didn't find any similar feature in user's settings, and it's definitely not available when typing a post.

Not sure if it's a Mangane issue (missing UI to trigger the feature) or a back-end issue (like the feature is totally missing on Akkoma itself)

**Comment by Cl0v1s** [comment]
I have to investigate this since the language field sent by akkoma is always empty. It status language doest not seem to be handled by Akkoma correctly.

**Comment by Cl0v1s** [comment]
Using 639-3 is a good idea, however we should keep in mind that someone 639-3 countries can break mastodon compatibility because of Eugen's opinionated position on languages

https://github.com/mastodon/mastodon/issues/18538#issuecomment-1139639976

**Comment by last-partizan** [comment]
This would be extremely useful.

And, also worth having ability to specify default "Post language", independently of "Interface language".

I have created following issue to track this in Akkoma:
https://akkoma.dev/AkkomaGang/akkoma/issues/750#issuecomment-11685

**Comment by last-partizan** [comment]
Oh, turned out we don't need any backend changes for this.

I'll start by trying to add this setting to akkoma-fe, and then here.

**Comment by Cl0v1s** [comment]
Resolved in https://github.com/BDX-town/Mangane/pull/332
