### ISSUE TITLE
Status streams are messing with user navigation

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#172]
Mangane currently propose a server push mecanism, where the app can subscribe to a status stream and update the UI when a new status is available in a TL. 

However this mechanism tends to mess with user scrolling, notably when getting back from a subsequent view. It cause a very frustrating UX, and is not really useful. Indeed normal navigation consists in scrolling down the page, so new status, placed at the top of the stack are not seen by user. 

I propose the following behaviour:
* We keep the streaming mechanism
* But it can not generate new status component, we only count the number of new statuses and warn the user that x statuses are available 
* That message is placed at the top of the UI, hovering and can be clicked to generate new status components and scroll the timeline to the top

We can also totally deactivate that mechanism, that can encourages social network addiction

**Comment by Dehelssey** [comment]
shouldn't that be solved by those options in settings ?
![image](https://user-images.githubusercontent.com/20315413/213669530-950004fb-67ce-44a8-b4af-0851e7ab191a.png)
> Automatically load new posts when scrolled to the top of the page

> Automatically load more items when scrolled to the bottom of the page

🤔

**Comment by Cl0v1s** [comment]
Nope changing this settings do nothing regarding streams, they are handled in a weird way and apprently they does not follow user parameters sometimes !

**Comment by Dehelssey** [comment]
oh. that's not the first time we have something in the UI not doing anything in the back... I blame you-know-who
