### ISSUE TITLE
Duplicate medias on posts from Friendica

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#174]
When we display a Friendica post, where images are contained within the post, they happen to be displayed **both** inside the post and as attachments below the post

post on friendica : 
![image](https://user-images.githubusercontent.com/20315413/213735260-28c90321-c366-48de-998a-cae512c560e0.png)

same post on mastodon : 
![image](https://user-images.githubusercontent.com/20315413/213735324-7998d8b3-4a31-444d-8ce1-19cdc1a6187e.png)

and finally on Mangane : 
![image](https://user-images.githubusercontent.com/20315413/213735373-e4a43ba8-2dcc-416b-98eb-9bad8d5616ea.png)

We should only display those medias once. Either inside the post or in the attachment section below.

**Comment by Cl0v1s** [comment]
Non reproduit, y compris sur le status montré en exemple :)
