### ISSUE TITLE
"New post" icon hidden by menu on mobile view

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#176]
When an instance has a long name, the local timeline menu entry, which inherits its name, takes 2 lines. Therefore the menu bar is bigger. And it hides the pencil icon to write a new post.
![213dbee903e1d66a2426421fba1bb7be62ef92919504f0d25a3f1e3d709fc1ea](https://user-images.githubusercontent.com/20315413/213809683-8a836fa9-4f70-4411-918c-5e6c4d606237.jpg)

Moreover, on this screenshot from an italian instance, even the "discover" and "direct messages" labels are too long to fit on one line.

Should we get the menu back to 4 items only ? Or add a text-overflow property so longer names are cut with an ellipsis ? 

## Quick fix
We should, **at the very least**, make the pencil icon float higher, its position based on the menu height, not calculated from screen bottom. 

And, while we're at it, center labels so they look better should they remain on two lines

**Comment by Dehelssey** [comment]
It's also worth noting that italian translation lacks some localization. See #148

**Comment by vinzv** [comment]
Looking at the German version of the mobile UI there are icon names too long and - even worse - there is no word wrapping possible:
![grafik](https://github.com/BDX-town/Mangane/assets/74432/a33e3917-99e0-49be-bafa-56d450256f00)

Wouldn't it make sense to just remove the names at all, like this?
![grafik](https://github.com/BDX-town/Mangane/assets/74432/697ff791-95ea-486d-990d-7394f620e1fa)

Maybe make icons slightly bigger and replace the "explore" icon. Other than that, the icons are pretty self-explanatory, imho.

**Comment by Dehelssey** [comment]
As a UX designer i'm always reluctant to remove labels for the sole purpose of making things "prettier" but i guess the icons are indeed self-explanatory, especially with the ones i used on previous, still undeployed, designs.

If ditching labels means a cleaner UI without losing any meaning in the process then i'm all in for it !

**Comment by vinzv** [comment]
For the desktop view, I would keep the labels. My proposal was solely for the responsive view as there is only little space.
A compromise would be the cropping you proposed already. Yet, it's not too pretty.

> Neighborhood being a proposition for renaming the "bubble" timeline

From my understanding the "bubble" timeline is something different from what the word "neighborhood" would describe:
Slightly philosophical speaking, you hardly can curate a neighborhood. A bubble, yes. But you can only pick a neighborhood to move there or build a new one with others moving there later on. So while I like the both the icon and the name per se, maybe something like "friendships" or "flock" might be more accurate?

**Comment by Dehelssey** [comment]
yup I understood the labels removal was only considered for the mobile view, i just happen to share the icons from a desktop view because I didn't applied them to mobile view yet 👀 

regarding Neighborhood i acknowledge that it's not really the most accurate word, hence it not being officially adopted^^

We wanted to keep the "local" pov for Mangane. So you have your home / your "local" timeline which is your hometown and i wanted the bubble to be like the network of friendly cities you're related to... like twin towns... I couldn't figure a better word yet but to be honest i feel like if "neighborhood" should be an official label here it would better apply to... the local timeline itself^^

Friendships or flock lacks the "city / town / real life geography" vibe i'm looking for. I'll keep scratching, but that'll be for another issue !

**Comment by Cl0v1s** [comment]
Maybe `peaceful-panther` maybe the navigation release we spoke about for such a long time ?
