### ISSUE TITLE
Issues with the colours and settings.

### ISSUE THREAD

**Issue by MadBloris** [BDX-town/Mangane#178]
I was using Mangane, and it worked fine. I updated last week and ran into problems with a few things.

![Screenshot 2023-01-26 101425](https://user-images.githubusercontent.com/56302540/214811371-cd26ddf5-5dcd-47bc-a5a8-9ddcbabd0c83.png)

It looks like this.

![Screenshot 2023-01-26 101511](https://user-images.githubusercontent.com/56302540/214811376-6b6caf4e-1ecc-4e21-9d94-07ffd45b2147.png)

You'll notice the brand colour and accent are set.

![Screenshot 2023-01-26 101527](https://user-images.githubusercontent.com/56302540/214811379-87e5ba96-803f-42a1-8b93-35176aa2f8c0.png)

The mangane config page does not seem to save anything if I change any settings. I can't manually edit the json data on the page, and if I do it via the terminal it does not seem to change a thing.

**Comment by Dehelssey** [comment]
I think your problem comes from the fact you're using black as accent color... Therefore it's not legible in dark mode.

**Comment by MadBloris** [comment]
I dont seem to be able to change it via the mangane config, if I manually do it (I just cp soapbox.example.json to test) it is still the same. 

![Screenshot 2023-01-26 112219](https://user-images.githubusercontent.com/56302540/214823874-5a6aec8b-bf74-421d-9495-1eca7f5996bb.png)
![Screenshot 2023-01-26 112201](https://user-images.githubusercontent.com/56302540/214823891-b20e6c53-5d66-4258-a25b-e5f43a42188f.png)

**Comment by Cl0v1s** [comment]
Is the problem solved if you change your accent color for something more readable ? 

A good practice is also to follow the WCAG recommendations http://colorsafe.co/

**Comment by MadBloris** [comment]
I've tried using the defaiult soapbox.json and it still remains. I CTRL + F5 after doing so. Deleted cookies, and tried a different browser.

It seems it is not pulling some of the changes (weird). I have no idea how to debug it on akkoma though

**Comment by Cl0v1s** [comment]
Where do you copy the example.json ? 
In the case of a use with Akkoma, the data is stored on the backend, and the JSON file doesn't seem to be used.

**Comment by MadBloris** [comment]
instance/static/frontends/mangane/dist/instance/

If I copy the soapbox.example.json to soapbox.json it seems to pull some settings from there

**Comment by MadBloris** [comment]
It has just occurred to me that I am running develop and not stable, could that be the cause?

**Comment by AdrianPaulCarrieres** [comment]
Same issue here with a brand new installation :/
(even with light theme):


<img width="1233" alt="image" src="https://user-images.githubusercontent.com/36892477/221404347-8ec3d1b5-ffa6-436c-a305-3529f03a41eb.png">

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/36892477/221404363-af76a5b3-9b8a-4b3e-bdfb-13b88b7f07ef.png">

**Comment by MadBloris** [comment]
Ha! I am glad it was not just me!

I never found a workaround. I recently reinstalled my server with 20.04 and used nginx instead of apache, which I was using before. 

I plan to play about one day, but for now, my akkoma is just running the pleroma-fe. I will post back if I find a solution

**Comment by AdrianPaulCarrieres** [comment]
It worked normally on "from source" install (not using OTP) with nginx on Ubuntu and Arch a few weeks ago at least
The only difference, for me, would maybe be Akkoma releases or the OTP release

**Comment by MadBloris** [comment]
Mine is from source.

Still no luck with a fresh install. I didn't think there would be, but I had to upgrade / reinstall anyway

**Comment by rebeccasaurus** [comment]
I just finished spinning up my own Akkoma-instance today and decided to give this frontend a go. It's very hard on the eyes to read black text on a dark background.. (it started like that when I switched it on)

**Comment by MadBloris** [comment]
Fixed with this issue. I guess they were linked? - https://github.com/BDX-town/Mangane/issues/202
