### ISSUE TITLE
Bug in chats in Light mode this time

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#179]
The chat module at the bottom right of the desktop page works fine.

However [the chat page](https://bdx.town/chats/) features that bug where text ins reply field is white on white background (similar to previous bug where text was black on black)
<img width="599" alt="image" src="https://user-images.githubusercontent.com/20315413/214820784-ea9d4c5f-4916-45b4-831f-7fa518e46f34.png">

note that this also affects chats on mobile since they only exist via this page there.

**Comment by Cl0v1s** [comment]
Chats are no longer supported
