### ISSUE TITLE
Missing icon in frontend

### ISSUE THREAD

**Issue by bugsysop** [BDX-town/Mangane#180]
This is on a Pleroma instance.

![ui-icon-bug-social@tmprs](https://user-images.githubusercontent.com/365281/215206191-a218de8a-a12f-4554-ac6e-ae9ba08db6f3.png)

**Comment by bugsysop** [comment]
Temporary solved with an eimoji but... It dosn't fit the global design

**Comment by Cl0v1s** [comment]
Hi ! 

You mean you want to use an instance's custom emoji to appear there ? :)
