### ISSUE TITLE
The "unblock" button can be too large and overflows on user's PP

### ISSUE THREAD

**Issue by uandreew** [BDX-town/Mangane#186]
In the Ukrainian localization, the "unblock" button becomes larger and climbs onto the user's avatar.

![image](https://user-images.githubusercontent.com/105280814/215354729-4953228b-4ab1-4613-9ce8-f6cfc9c0f675.png)

**Comment by Dehelssey** [comment]
we should max-width the hell out of this button, it doesn't really matter if it goes two-lines

**Comment by Cl0v1s** [comment]
I fixed that in the translations files for your language. 
Can you please review this MR to be sure that the edited translations kept their meaning ? 

https://github.com/BDX-town/Mangane/pull/245

**Comment by Dehelssey** [comment]
I just realized that we could simplify those buttons by removing the handle of the person we wanna unblock. I mean, we're right on their profile page i'm pretty sure a simple "unblock" button would be enough^^

**Comment by Dehelssey** [comment]
and... i'm two weeks late since it appear it's exactly what you've done @Cl0v1s >_<
