### ISSUE TITLE
Either change the icon of error notifications OR allow user to close them

### ISSUE THREAD

**Issue by sleroq** [BDX-town/Mangane#188]
At the moment, you can't close notification by clicking on this icon.

![image](https://user-images.githubusercontent.com/52239427/216691676-d74f8885-9604-4c22-87ff-eb19599fb0eb.png)

**Comment by Cl0v1s** [comment]
It's because that's not a close button, but a "error" icon. 
That's indeed confusing

**Comment by Dehelssey** [comment]
We should totally change the icon OR, even better, allow user to dismiss those notifications (either by clicking the X or swiping them out ?)
