### ISSUE TITLE
Inconsistent throttling notifications

### ISSUE THREAD

**Issue by sleroq** [BDX-town/Mangane#189]
When subscription request fails, there is only one message:
![image](https://user-images.githubusercontent.com/52239427/216692155-9db0f556-dbcf-442d-9a54-156207139d94.png)

But when enabling notifications fails - there are two:
![image](https://user-images.githubusercontent.com/52239427/217198981-6016b24e-fcb8-4518-8690-a294ca287038.png)

**Comment by Cl0v1s** [comment]
Probably because there is an error from the main thread and one error from the service worker.
