### ISSUE TITLE
Where should I open issues?

### ISSUE THREAD

**Issue by sleroq** [BDX-town/Mangane#190]
Issues link on [contributing.md](https://github.com/BDX-town/Mangane/blob/master/docs/contributing.md#contributing-to-soapbox) leads to soapbox repository.

But, as far as I understand, this is an independent project.

I think it would be a nice to correct contributing.md or add more information on creating new issues.

**Comment by Dehelssey** [comment]
Woops, i thought we recently rewrote every doc to update mentions of soapbox 😩

**Comment by konart** [comment]
https://github.com/BDX-town/Mangane/blob/master/docs/customization.md is also still soapy

**Comment by bugsysop** [comment]
I will try to correct this ASAP…
