### ISSUE TITLE
.atom instead of HTML page for hashtag searches

### ISSUE THREAD

**Issue by ymollard** [BDX-town/Mangane#193]
Open this link in a browser in which you are not logged in: https://bdx.town/tags/rosconfr
It downloads a .atom file instead of serving the HTML, it looks like a bug.

**Comment by uandreew** [comment]
Everything works fine for me, I don't think it's a bug.

Try clearing your cookies and cache, it might be because of this.

**Comment by Cl0v1s** [comment]
I can repro

**Comment by Cl0v1s** [comment]
It occurs when attempting to access this link without having 'Mangane' in your cache. (Reproducible by force-reloading the page.)"

Since it specifically occurs when Mangane is not loaded, I don't believe this is a bug caused by Mangane. It seems to be a URL collision with a native Akkoma feature.
