### ISSUE TITLE
txt files

### ISSUE THREAD

**Issue by uandreew** [BDX-town/Mangane#194]
Why does Mangane open txt files in a different window instead of downloading the file to the computer?

**Comment by Dehelssey** [comment]
I presume it handles all medias the same way : images open in the browser, music plays in the browser, video plays in the browser, PDFs open in the brower... so does txt files.

I don't like my device to download stuff I just wanna display but I'm open to your arguments^^

**Comment by uandreew** [comment]
I'm all for it opening txt in the browser, but I have a problem with the encoding... Akkoma doesn't want to understand Cyrillic text properly and shows unintelligible characters...
