### ISSUE TITLE
problem with UI mangane

### ISSUE THREAD

**Issue by uandreew** [BDX-town/Mangane#195]
![image](https://user-images.githubusercontent.com/105280814/221378616-4766e375-e51e-491e-b787-d4e59e8066bb.png)

a user of my instance writes that he has a problem with the interface, I advised him to clear the cache and cookies, but it didn't help, what should I do?

**Comment by uandreew** [comment]
![image](https://user-images.githubusercontent.com/105280814/221378676-20141287-bbae-47f0-9264-b923bd4f2d28.png)

**Comment by Cl0v1s** [comment]
What is exactly the issue with your first two se
