### ISSUE TITLE
[Feature request] - Remove possibility to change creds when using ldap

### ISSUE THREAD

**Issue by meaz** [BDX-town/Mangane#196]
Hi,

we're using akkoma with ldap. We don't want our users to be able to change their email and password from the frontend. At the moment, If you attempt to change/update the email address or the password mangane/akkoma returns an "Update failed" message.

But that would be awesome if the possibly to even try could be removed from the Security options list in the Settings page.

**Comment by Cl0v1s** [comment]
Hi ! Thanks for the idea :)

**Comment by meaz** [comment]
Hi @Cl0v1s I've just upgraded to vwondering-wapiti-2e3c1c3 but I still see the possibility to change email or password whereas we use LDAP. Is there a setting I need to set somewhere?

![mangane](https://github.com/BDX-town/Mangane/assets/13604424/e8eb3953-d39f-4d16-91c4-c8446326a2b0)
