### ISSUE TITLE
Questions about reactions to posts

### ISSUE THREAD

**Issue by uandreew** [BDX-town/Mangane#201]
![image](https://user-images.githubusercontent.com/105280814/232246804-962a94dd-79f8-451f-a8e3-98697803d03c.png)
Can we add more emojis for reactions to posts?
By editing the code or some other way?

**Comment by uandreew** [comment]
I figured out how to add emojis to reactions.

If anyone is interested, write either here or in Fediverse @ihor@ak.noleron.com, I'll tell you what I did to add emojis)

![image](https://user-images.githubusercontent.com/105280814/232250144-d0da1393-4996-4dc8-a9db-500302b1c1ae.png)

**Comment by uandreew** [comment]
![image](https://user-images.githubusercontent.com/105280814/232250939-001a47ff-1c8d-4b1b-aea4-26196334b4ae.png)
the only problem is that if there are a lot of emojis, the page breaks

**Comment by Sevichecc** [comment]
The reaction emoji in [kongwoo.icu](mangane.kongwoo.icu) is duplicated, I don't know how to solve this yet, do you know where to change this ?
<img width="520" alt="image" src="https://user-images.githubusercontent.com/91365763/233705366-9f3a2557-3b6a-4ac8-9006-cba87330a7a8.png">

**Comment by uandreew** [comment]
> The reaction emoji in [kongwoo.icu](mangane.kongwoo.icu) is duplicated, I don't know how to solve this yet, do you know where to change this ? <img alt="image" width="520" src="https://user-images.githubusercontent.com/91365763/233705366-9f3a2557-3b6a-4ac8-9006-cba87330a7a8.png">

https://github.com/ua-thinking/ak.noleron.com/commit/2d20b259f95b0a895d376a43890d523c189d0781 

It's better to roll back all the changes and see how I added emojis in this repository and repeat it. But again, a large number of emojis broke the interface on mobile version.

**Comment by Sevichecc** [comment]
> > The reaction emoji in [kongwoo.icu](mangane.kongwoo.icu) is duplicated, I don't know how to solve this yet, do you know where to change this ? <img alt="image" width="520" src="https://user-images.githubusercontent.com/91365763/233705366-9f3a2557-3b6a-4ac8-9006-cba87330a7a8.png">
> 
> [ua-thinking@2d20b25](https://github.com/ua-thinking/ak.noleron.com/commit/2d20b259f95b0a895d376a43890d523c189d0781)
> 
> It's better to roll back all the changes and see how I added emojis in this repository and repeat it. But again, a large number of emojis broke the interface on mobile version.

Thank you! I will try that later

**Comment by uandreew** [comment]
> > > The reaction emoji in [kongwoo.icu](mangane.kongwoo.icu) is duplicated, I don't know how to solve this yet, do you know where to change this ? <img alt="image" width="520" src="https://user-images.githubusercontent.com/91365763/233705366-9f3a2557-3b6a-4ac8-9006-cba87330a7a8.png">
> > 
> > 
> > [ua-thinking@2d20b25](https://github.com/ua-thinking/ak.noleron.com/commit/2d20b259f95b0a895d376a43890d523c189d0781)
> > It's better to roll back all the changes and see how I added emojis in this repository and repeat it. But again, a large number of emojis broke the interface on mobile version.
> 
> Thank you! I will try that later.

I was happy to help!

If you find out how to solve the problem on the mobile version, I hope you'll share the solution)

**Comment by Cl0v1s** [comment]
If you have some time, it would be awesome if you could explain how you did it in a special documentation for example !

**Comment by uandreew** [comment]
> If you have some time, it would be awesome if you could explain how you did it in a special documentation for example !

I have some time, and in about an hour I will make a special documentation)

I think I'll do it with Markdown, maybe can move the file to /tree/master/docs later?
