### ISSUE TITLE
dashing-peacock upgrade: dark is all dark

### ISSUE THREAD

**Issue by gerwitz** [BDX-town/Mangane#202]
Doing a normal upgrade on my Akkoma instance to dashing-peacock (from wrestling-red-panda) resulted in dark mode rendering dark text on a dark background on most content, except the posts feed of an individual profile.

**Comment by gerwitz** [comment]
This is only partially visible when not logged-in: https://social.gerwitz.com/

**Comment by Cl0v1s** [comment]
Hi ! 

What is your new version of Akkoma ? 
There new stricter Content-policy prevent third party frontend from retrieving instance configuration. Do you see something related to CSP in your browser logs ?

**Comment by Cl0v1s** [comment]
The solution is to override the Content-policy header in your nginx/apache configuration, to allow style-src :)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by uandreew** [comment]
or, if you're lazy or don't want to bother with it, you can roll back the security policy update and everything will work.

https://akkoma.dev/AkkomaGang/akkoma/commit/336d06b2a8ca75362578b1d67ea1f32a45c8edd3

**Comment by Cl0v1s** [comment]
If you choose the solution to edit your reverse proxy Content-Policy header, i'm interested in your solution, so I can add it to the Readme on here :)

**Comment by uandreew** [comment]
> If you choose the solution to edit your reverse proxy Content-Policy header, i'm interested in your solution, so I can add it to the Readme on here :)

I still haven't found the time to set up the content-policy, so I'm still using the solution I wrote before this.

**Comment by AdrianPaulCarrieres** [comment]
I've never done this kind of stuff with nginx but so far my solution is to 1) hide the Content-Security-Policy header, 2) set it again with the copy pasted original header with a change in the `style-src` part:

```
    # add style-src for mangane
    proxy_hide_header Content-Security-Policy;
    add_header Content-Security-Policy "upgrade-insecure-requests;style-src 'self' 'unsafe-inline';font-src 'self';script-src 'self' 'nonce-LbVARBmXD6txCer';connect-src 'self' https://example.com wss://example.com;media-src 'self' https:;img-src 'self' data: blob: https:;default-src 'none';base-uri 'none';frame-ancestors 'none';manifest-src 'self';";
```

The change by itself is 
`style-src: 'self' 'nounce-xxxxxxxx';`
becomes
`style-src: 'self' 'unsafe-unline;'

**Comment by muppeth** [comment]
Shouldn't akkoma permit mangane to work out ocf the box? Perhaps good to check with the main devs there @Cl0v1s 
It would make things much easier. I will try to update csp for now as for people running OTP version rolling back isnt possible.

**Comment by Cl0v1s** [comment]
Since they unilateraly changed this security setting, and do not seem to have any interest in supporting a frontend beside their own, I think we could just instead clearly explain how to override CSP in Mangane's documentation.

I'll try to propose something based on @AdrianPaulCarrieres's answer :)

**Comment by muppeth** [comment]
Is there any link where akkoma devs stste such thing? I think since they now work on feature that allows frontend switch, they are more open to others

6 May 2023 18:37:32 Clovis ***@***.***>:

**Comment by Cl0v1s** [comment]
I read that on some comments to a open issue in the Akkoma repo, but you're right, maybe their position changed since then !

**Comment by Cl0v1s** [comment]
Readme updated

**Comment by mmai** [comment]
Hi @Cl0v1s there is a typo on the Readme : you wrote `proxy_hide_header Content-Security-Policy:`  with a ':' instead of `proxy_hide_header Content-Security-Policy;` with a ';'

**Comment by Cl0v1s** [comment]
Thanks, I fixed that !
