### ISSUE TITLE
Unable to import when using Mangane

### ISSUE THREAD

**Issue by jcrabapple** [BDX-town/Mangane#206]
When I have Mangane enabled on my Akkoma instance and set as primary, users are unable to import CSVs. There is a 404 error on /api/v1/pleroma/blocks_import.

**Comment by Cl0v1s** [comment]
Hi ! That's probably related to recent changes on Akkoma about the /v1 endpoints. 

Does it seem something like it @uandreew  ? :)

**Comment by Cl0v1s** [comment]
It's because this particular endpoint is not in v1

https://docs.akkoma.dev/stable/development/API/pleroma_api/#apipleromablocks_import

Are you using the latest version of Akkoma @jcrabapple  ?

**Comment by jcrabapple** [comment]
I'm using Yunohost so I'm running 3.7.1.

**Comment by Cl0v1s** [comment]
Thanks for your quick response, I have a fix !

**Comment by uandreew** [comment]
> Hi ! That's probably related to recent changes on Akkoma about the /v1 endpoints.
> 
> Does it seem something like it @uandreew ? :)

Oh, yeah)
I guess I missed import/export)
And the links are broken)
