### ISSUE TITLE
Chat won't display send message as soon as they're sent

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#219]
When using the chat, whether in the main window or via the chat box in the corner, the messages I send are not displayed. I have to refresh the window to see them.

**Comment by Cl0v1s** [comment]
Made a poll on bdx.town to see if people still use chat. If not, will drop their support here too since they arent supported by Akkoma

**Comment by Cl0v1s** [comment]
(The issue seem to be on Akkoma side, the streaming endpoints since to have been removed)

**Comment by Cl0v1s** [comment]
Chats are no longer supported by Mangane
