### ISSUE TITLE
Quoting toots disable CW

### ISSUE THREAD

**Issue by AdrianPaulCarrieres** [BDX-town/Mangane#225]
Quoting a toot disable its CW, and adding to the quoting toot a CW still display the content of the CWed toot.

![245889589-84170606-406a-4190-9291-551c93c2f42a](https://github.com/BDX-town/Mangane/assets/36892477/f173c5e5-18e9-41a3-afdb-78b8a4368c40)

Instead, both toots should be CW'ed

**Comment by Cl0v1s** [comment]
Indeed that an important issue. Will try to work on it soon
