### ISSUE TITLE
[Feature Request] Follow hashtags 

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#232]
Akkoma supports following hashtag since a few months now.
Add that feature to mangane ! 

https://meta.akkoma.dev/t/akkoma-stable-2022-12-automatic-static/225

**Comment by Cl0v1s** [comment]
We need to add : 

* An option to follow hashtags from a hashtag feed (from search)
* An option to see all followed tags
* An option to unfollow a tag
* Mean to navigate between the new hashtag timelines

**Comment by Cl0v1s** [comment]
@Dehelssey do you have a take on those points ?

**Comment by Dehelssey** [comment]
@Cl0v1s I assume none of these have UI in Mangane or in the soapbox base so far ? I'll have to take a look and think of a way to display and manage them !!

**Comment by Cl0v1s** [comment]
Since we are really far from a working rewrite, let's continue to maintain this base code ! 

Also, what do you think about putting a separate section for hashtags in the UI ?

https://www.theverge.com/23673125/mastodon-separate-tags-hashtag-navigation-accessibility

It would be added to actual toot content eventually but allows us to make some improvement regarding accessibility

**Comment by Cl0v1s** [comment]
I think there is a fully compatible way of doing this: 

On mangane, we provide a dedicated space for hashtags when writing. When sending those tags are added at the end of the toot.
When reading, we show the content normally. 

In this way our users could have a dedicated space, maintain readability, while being still fully compatible with everyone

**Comment by Dehelssey** [comment]
yes, that would be a start, while hopefully waiting for more tools to get on the train ! (like, tumblr, don't let us down)
