### ISSUE TITLE
Filters does not work

### ISSUE THREAD

**Issue by Animaly0** [BDX-town/Mangane#234]
Comme discuté dans ce fil : https://peculiar.florist/notes/9gw2j2z6rojno985

Les filtres de mots semblent ne pas fonctionner sous Mangane alors q’ils fonctionnent sous akkoma-fe.

**Comment by Cl0v1s** [comment]
Filtering is done client-side. We are indeed probably the issue here.

https://docs.joinmastodon.org/methods/filters/#get-v1
