### ISSUE TITLE
Allow exporting CSV backups of user data (follows, mutes, blocks)

### ISSUE THREAD

**Issue by csolisr** [BDX-town/Mangane#236]
Currently, it's possible to import CSV backups of user data from the interface, but not to export them. Soapbox had removed the ability to do so (probably due to instability?) but has already restored that functionality in later patches:

https://gitlab.com/soapbox-pub/soapbox/-/commit/e50e4b8e608de927bb64405aec4d50d1104e7c25

https://gitlab.com/soapbox-pub/soapbox/-/commit/658e336e5c2ff371eced8bc131f044831c158912

https://gitlab.com/soapbox-pub/soapbox/-/commit/21f864c8a61f3669acbf19f062d240b0f9ea3d68

Is it possible to import these patches from upstream and apply them to Mangane?

**Comment by Cl0v1s** [comment]
Is this not the contrary ? We indeed have an interface to import backups, but not to create them
![image](https://github.com/BDX-town/Mangane/assets/917518/4fa0fae3-0950-448c-8584-0f9de12e85a2)

**Comment by csolisr** [comment]
Wait you're right, I had it backwards, let me edit the name of the bug...

**Comment by Cl0v1s** [comment]
So yeah, it's one of my priority since it's not fair to "capture" users without an easy way for them to migrate. 

Thanks for pointing out the commits, I'll try to see if we can cherry-pick them :)

**Comment by csolisr** [comment]
Sorry for bothering, just to know if you've had time to check the commits to cherry-pick them. Otherwise I could see if I can add them manually to a pull request this weekend

**Comment by Cl0v1s** [comment]
Thanks for offering your help ! I've finally done it so it will be available in the next release :)
