### ISSUE TITLE
Markdown rendering 

### ISSUE THREAD

**Issue by foxmask** [BDX-town/Mangane#256]
Hi,
when I post stuff like that in Markdown 

```
# my title 1

## my subtitle 1.1

* item1
* item2
* item3

### my subtitle 1.2

| One |  Table |
| ------ | --------------- |

### my subtitle 1.3

| Another | Table |
| ------ | --------------- |

```

I have several rendering issues:

1 - the H1 and H2 are not formatted as they should be (in bold with their own size)
2 - the blank line between heading and the next paragraph (text or table or anything) are dropped  BUT, not for the last paragraph after the heading

if I put 8 headings + 8 tables eveything is trim except the 8th one which is correctly formatted

you can have a look of that behavior [here ](https://bdx.town/@foxmask/posts/AZ0mJ5keRmtHdu9v04https://bdx.town/@foxmask/posts/AZ0mJ5keRmtHdu9v04)

**Comment by Dehelssey** [comment]
something's wrong with your link : it's pasted twice and it results in an error URL ^^

here's the right one : https://bdx.town/@foxmask/posts/AZ0mJ5keRmtHdu9v04

all tables looks the same to me, none of them really OK even tho we see 2 columns.

We could totally change font-size and/or boldness of headings as well

**Comment by foxmask** [comment]
We can close that issue, i'll manage that in another way. 

That will be more simple for everyone ;)

I added link of the tables in markdown file I host on a repo.

Eg

https://bdx.town/@foxmask/posts/AYynmn54wCuPzgL2gq
