### ISSUE TITLE
Can't vote on a poll on the main timeline

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#258]
Whenever i try to vote on a poll that appears in my feeds, the click on the option i select is considered as a click on the post and opens it in focused mode.

see video below:

https://github.com/BDX-town/Mangane/assets/20315413/47975093-5597-47c9-aef0-de3722ba4f9c

I'd rather be able to vote without leaving the main feed.

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/298/files
