### ISSUE TITLE
Mangane's new logo

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#260]
Hi @Cl0v1s!

As requested, here are the SVG of various versions of the new logo. Icon + text (vertical/horizontal) and icon only versions for both light mode and dark mode!

You'll also find a SVG and a PNG of a square version with background for a social media presence for instance

[LOGO.zip](https://github.com/BDX-town/Mangane/files/12916936/LOGO.zip)

**Comment by Cl0v1s** [comment]
Thanks ! I will add this to the project during my winter vaccations !

**Comment by wakest** [comment]
oh cool Mangane has a logo now! I had chatted about this ages ago, glad to see this!

**Comment by Cl0v1s** [comment]
fixed in 7c1ebc21af3667d8eb1c672474eb770bd29d5de3
