### ISSUE TITLE
Scheduled post alert remains after scheduled post is published

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#261]
I've scheduled a post for yesterday.

Today when i publish a new post, i still have the alert that i have a scheduled post when i actually don't (you can see it in the screenshot, in the background)
<img width="631" alt="image" src="https://github.com/BDX-town/Mangane/assets/20315413/0cbbd144-fde4-47d0-94cc-94e4f00f2f30">

**Comment by Cl0v1s** [comment]
Duplicate, done is latest release :)
