### ISSUE TITLE
Installing as a secondary frontend

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [BDX-town/Mangane#265]
Most of the users on my instance prefer the default pleroma-fe, but we still want to experiment with Mangane, is there a way to install it such that it uses a url, like how mastodon-fe shows up as [url]/web?

**Comment by Cl0v1s** [comment]
Hi ! 

To use Mangane as a secondary frontend, you need to: 

* Set the BACKEND_URL var env to your backend and build it 
* Deploy the newly build mangane on a subdomain for instance: mangane.your-domain.tld

https://github.com/BDX-town/Mangane#backend_url
