### ISSUE TITLE
Can not 'Block notifications from strangers'

### ISSUE THREAD

**Issue by meaz** [BDX-town/Mangane#268]
Log in mangane, go to `Edit profile` and enable `Block notifications from strangers`. If you `Save` but leave and come back, the option is not active anymore.

**Comment by Dehelssey** [comment]
just tested and it indeed doesn't work ! thanks for noting this :)

**Comment by Cl0v1s** [comment]
That's an issue on akkoma side: the doc is saying that the data must be provided in the request body while in facts (and in their tests) it's provided in the request uri

https://docs.akkoma.dev/stable/development/API/pleroma_api/#apipleromanotification_settings

https://bdx.town/api/pleroma/notification_settings with body { block_from_strangers: true } -> innefective

https://bdx.town/api/pleroma/notification_settings?block_from_strangers=true -> setting actually changed

**Comment by Cl0v1s** [comment]
Issue created there, i'll add a fix on our side for now
https://akkoma.dev/AkkomaGang/akkoma/issues/722

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/277
