### ISSUE TITLE
Like button focus area is over-large and can obstruct posts

### ISSUE THREAD

**Issue by rjp** [BDX-town/Mangane#272]
Using Safari Version 17.4 (19618.1.13.11.5), the like button (heart icon) activates its emoji popup when you're merely hovering nearby, not over the button itself.

Example screenshots (which caused me to accidentally emoji this post instead of clicking on the link)

Moving towards the link:

<img width="696" alt="Screenshot 2024-03-02 at 11 11 59" src="https://github.com/BDX-town/Mangane/assets/10793/70720141-10fb-480e-8053-0c6a2c4d19dc">

Over the link but the emoji panel has popped up instead

<img width="685" alt="Screenshot 2024-03-02 at 11 12 01" src="https://github.com/BDX-town/Mangane/assets/10793/caf07df2-4cf6-47ab-81f7-caa29435a0df">

Seems like the target hover area for the emoji popup is that of the emoji popup itself rather than just the heart icon?

**Comment by Cl0v1s** [comment]
Hi that's an interesting issue indeed, will look into that !

**Comment by Dehelssey** [comment]
On Version 17.3.1 (19617.2.4.11.12) i don't have the issue 🤔 
I'll update MacOS, brb^^

**Comment by Cl0v1s** [comment]
Reading the code, I can see it's a bit weird on this part, and I think I know how @rjp can produce that situation. 

Thanks for your repros @Dehelssey !

Since i'm working on custom emojis reaction on posts, I'm reworking that emoji bar a bit so I will try to fix that issue too

**Comment by Cl0v1s** [comment]
Should be fixed with https://github.com/BDX-town/Mangane/pull/280
