### ISSUE TITLE
Darkmode  issue

### ISSUE THREAD

**Issue by pagenstedt** [BDX-town/Mangane#274]
I recently migrated from pleroma/soapbox to akkoma/mangane. I really like this frontend due to its simpleness. 

However, I am not able to run darkmode. The text color will not change to white.
![Bildschirmfoto vom 2024-03-13 13-13-50](https://github.com/BDX-town/Mangane/assets/37019399/e1237ebf-4445-4e46-b836-fce31cc1a4c1)

Since I am new to mangane: Where would I be ablle to customize the colors in css?

Thanks!

**Comment by Cl0v1s** [comment]
Hi ! 

It looks like you're having some issues with CSP, did you try to follow those instructions ? 

https://github.com/BDX-town/Mangane?tab=readme-ov-file#messy-colors--style-configuration

**Comment by pagenstedt** [comment]
Oh wow, that was a quick fix ineed. Thank you, works fine now. 
Please go on with your great work here.

**Comment by pagenstedt** [comment]
Sorry, @Cl0v1s one more question.
What about the grey color in the button. It is not a caching problem and color changes apply in json. Would this still be a CSP problem?
![Uploading Bildschirmfoto vom 2024-03-13 14-02-06.png…]()

**Comment by Cl0v1s** [comment]
Do you have any error mentioning CSP in your browser console ? :)

**Comment by pagenstedt** [comment]
> Do you have any error mentioning CSP in your browser console ? :)

@Cl0v1s  Yes, it seems quite a few. 

![errors](https://github.com/BDX-town/Mangane/assets/37019399/fbf4e685-62a8-4824-a7c5-e68713feb1b5)

**Comment by pagenstedt** [comment]
I did put this in my nginx config, as instructed. maybe something missing?
