### ISSUE TITLE
Searchbox in emoji picker focuses on global searchbox when pressing "S"

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#289]
I noticed this because i was trying to add the weat_smile emoji (😅) ^^

see screen capture:
Uploading Enregistrement de l’écran 2024-03-25 à 10.56.04.mov…

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/300

**Comment by Dehelssey** [comment]
you're UNSTOPPABLE right now !
