### ISSUE TITLE
Navigation item's focus are slightly cropped

### ISSUE THREAD

**Issue by graphmatth** [BDX-town/Mangane#290]
Hi!

Congratulation for this new UI version! 🎨

I create this issue to indicate that the navigation item's focus are slightly cropped.

After a quick inspection, a possible solution is to update the `outline-offset` property on the link :

```css
outline-offset: -1px; 
```

The screenshots where taken on Google Chrome. Let me know if you need more information 🙂.

![image](https://github.com/BDX-town/Mangane/assets/17874855/7901e8dd-b711-46af-bfa8-c5f44a2aac9b)
![image](https://github.com/BDX-town/Mangane/assets/17874855/43f0fefe-468c-41ca-baa0-a952a6e2eb3a)

**Comment by Cl0v1s** [comment]
Thanks @graphmatth !

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/321
