### ISSUE TITLE
Logout link appearance

### ISSUE THREAD

**Issue by graphmatth** [BDX-town/Mangane#291]
Hi!

I create this issue to share a UX feedback.

I find the "logout" cta a little lost and a bit confusing, maybe it would be worth putting it forward ?

This is very subjective and may be clear to other users, but I just wanted to share my feedback 🙂

![image](https://github.com/BDX-town/Mangane/assets/17874855/81a58375-542c-4e92-a2d4-aba1dc8293e5)

**Comment by Dehelssey** [comment]
Indeed, tbh i think we can totally remove it from this column and leave it only in the dropdown when clicking our PP 
![Screenshot_20240325-232957_Vivaldi](https://github.com/BDX-town/Mangane/assets/20315413/fb4840fb-e06b-4770-b2e9-a857d6dc45d9)

**Comment by Cl0v1s** [comment]
Fixed in https://github.com/BDX-town/Mangane/pull/301
