### ISSUE TITLE
Dropdown user position

### ISSUE THREAD

**Issue by graphmatth** [BDX-town/Mangane#292]
Hi!
Another UX Feedback, I find that this dropdown is a bit of a duplicate with the account info overlapping, maybe lower it below the info block to separate it?

Again, this is subjective and may be clear to other users, but I just wanted to share my feedback!

Have a good day! 🙂

Matthieu

![image](https://github.com/BDX-town/Mangane/assets/17874855/03a4f8da-e871-483c-ab94-498362700c7c)

**Comment by Cl0v1s** [comment]
I makes more sense when two accounts are logged in. But I think we can make that dropdown more visible compared to the background :)

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/322
