### ISSUE TITLE
Translation missing in mobile navigation

### ISSUE THREAD

**Issue by pagenstedt** [BDX-town/Mangane#299]
"communauté" seems to be missing in translation file.

![nav](https://github.com/BDX-town/Mangane/assets/37019399/e8730211-f73b-4476-b01c-b1555f7050c1)

**Comment by pagenstedt** [comment]
Yes, german indeed :) However, I think "Community" would be the right term in german as well as in english.

**Comment by Dehelssey** [comment]
BTW, english version of Mangane was also displaying french label ;)

**Comment by Cl0v1s** [comment]
Fixed in https://github.com/BDX-town/Mangane/pull/305
