### ISSUE TITLE
Feature Request: link the Profile Picture in the sidebar to own profile page (on desktop)

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#302]
Currently your Profile Picture in the sidebar isn't clickable.

Username opens a dropdown where you can find a link to your profile page but i think we could save an extra click by making the PP a link to public profile page.

I often go to my profile page to get the link of one of my pinned posts or to find older posts or boosts i want to share or interact with, but i'm not sure it's a really common practice now that i  think of it

**Comment by Cl0v1s** [comment]
Good idea

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/306
