### ISSUE TITLE
Single user instance accessed while unauthenticated shows "invalid credentials" error

### ISSUE THREAD

**Issue by rudism** [BDX-town/Mangane#313]
I recently install Mangane on my Akkoma instance (previously using pleroma-fe). I've enabled unauthenticated viewing of profiles and single-user instance in the Mangane settings. I've noticed that when I access it while unauthenticated (in a private window, for example) this invalid credentials error pops up:

![image](https://github.com/BDX-town/Mangane/assets/4787751/5fab4883-283d-4b9b-b316-510fc6e37d67)

Looking at the network access tab in debug tools shows it's because it's accessing an `endorsements` API that seems to throw a 403 error when called while unauthenticated:

![image](https://github.com/BDX-town/Mangane/assets/4787751/fb756e5a-0403-4667-be91-2046dbdc196a)

I'm not sure if it's because of some other configuration I have somewhere--I can't find any mention of endorsements in the admin-fe frontend.

**Comment by Cl0v1s** [comment]
Thanks for the debug informations you provided, it seems there is a legacy call to that endorsements endpoint that requires user to be authenticated

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/320

**Comment by z411** [comment]
Hi, I'm using the latest version (1.13.6) and i'm having the same issue. It's getting a 403 in a call to `/api/v1/push/subscription` this time.
