### ISSUE TITLE
How to add custom CSS?

### ISSUE THREAD

**Issue by paulo-roger** [BDX-town/Mangane#325]
Please how can I add custom CSS to Mangane?

**Comment by paulo-roger** [comment]
![image](https://github.com/BDX-town/Mangane/assets/103009333/b8f26de1-3fbd-4854-a525-4dbd69451b6a)

I have tried this but doesn't seem to work

**Comment by Cl0v1s** [comment]
Hi ! 

I don't think we are supporting this kind of parameters as of today :)
