### ISSUE TITLE
Bad Request: empty form submitted

### ISSUE THREAD

**Issue by Fastidious** [BDX-town/Mangane#333]
I am getting this message on the right hand side of the screen (Chrome desktop, Linux). It is not a show stopper, but it is odd.

`Bad Request: empty form submitted`

It happens, mostly, when I click on "Notifications", and then click on "All", and "Mentions".

**Comment by Fastidious** [comment]
This also happens when I toggle settings.

**Comment by Cl0v1s** [comment]
Hi ! Which backend are you using ?

**Comment by Fastidious** [comment]
Hello! I am using GoToSocial.

**Comment by Cl0v1s** [comment]
Mangane is only tested and developed for Akkoma sadly, the issue is probably there :/
