### ISSUE TITLE
Ability to pin several posts

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#40]
Most instances/softwares allow this. It's frustrating to only be able to pin one post at a time.

Moreover you have to manually unpin the one you have before pinnin a new one ! 

Could we 
1. Be able to pin multiple posts
2. Or, at least, be prompted with a message asking us if we wish to unpin the current pinned posts and replace it with the new one ?

Feels like option 1 is both easier to implement and useful for people 🤷

**Comment by Cl0v1s** [comment]
It was an option in Akkoma. I set max pinned posts to 5. 

I'll still fix some translations in french tho.
