### ISSUE TITLE
Add a more visible indicator of posts' privacy level

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#46]
Pour ne pas compter que sur l'icône globe / cadenas ouvert / cadenas fermé finalement assez discrète, pourrait-on envidager un traitement (optionnel?) plus lisible de la confidentialité d'un post que l'on consulte ?

Par exemple un background différent ? Pour éviter l'effet patchwork ça peut être un motif en opacité.

GlithSoc propose une option ou chaque icone adopte une couleur différente + visible.

**Comment by Cl0v1s** [comment]
C'est une excellente idée. 
Tu as des idées de couleurs ? Le soucis étant que le système de couleur dans Mangane étant uniquement axé autour de 

1. Couleur de fond (Foncé / Clair)
2. Couleur d'accent 
3. Couleur primaire 

On risque d'être un peu limité. On peut imaginer un calcul sur la couleur primaire ? (Genre changement de teinte de 10% etc ?)

**Comment by Dehelssey** [comment]
ouais je me disais bien que les couleurs c'était ptet pas l'idéal d'où la propale d'un motif en opacité (hachuré diagonal, damier...)

ou alors juste une border ? couleur d'accent pour les non listé et couleur primaire pour les followers only ? c'est quoi les teintes en question ? c'est le orange actuel l'accent ? et la primaire du coup ? noir ou blanc selon le fond ? 

ça donnerait 
public → no border
non-listé → bordure de la même couleur que le texte
followers only → bordure orange 

et les direct alors ? >_<

**Comment by Dehelssey** [comment]
ouais la couleur ça suffira pas. je reviens encore à mes textures de bg du coup ^^

mais si on a couleur + icone bien mise en avant why not (mais tu la mets comment en avant l'icone si c'est pas avec une couleur différente ? plus grosse ? =/

**Comment by Cl0v1s** [comment]
Plus grosse mieux placée ? Sauf erreur de ma part ajd excepté les statuts privé et followers only, y'a pas de moyen de voir si c'est un statut public ou non visible sur les TL

Le 12 novembre 2022 19:37:11 GMT+01:00, "Guérin" ***@***.***> a écrit :

**Comment by Cl0v1s** [comment]
Du coup on tranche quelque chose ?

**Comment by Dehelssey** [comment]
Je te fais 2 3 propales asap 🙏

**Comment by Cl0v1s** [comment]
Top merci ! 

Le 25 novembre 2022 17:50:28 GMT+01:00, "Guérin" ***@***.***> a écrit :

**Comment by Dehelssey** [comment]
OK i'm dumb... it only occurred to me today that Mangane doesn't display post confidentiality on **all** posts. Right now, like you, @Cl0v1s , stated in a previous message (which i've never read before) only followers only and private posts have an icon, which takes the place of the "boost" one.

Therefore this should actually be a top priority cause for the moment you can see your post confidentiality **while** typing it but after that, it's over. And you can't edit it.

I'll try to propose something this weekend 😩

**Comment by Dehelssey** [comment]
here are my suggestions for different backgrounds textures depending on post privacy : https://arc.net/e/524A1C0A-C471-4885-BF85-2734FA05A3A7

Provided CSS uses hexas, you might wanna replace those by Mangane variables. Let me know i you want me to do it :) 

I suggest we also add the right icon before the "answer / boost / react" ones :
![image](https://user-images.githubusercontent.com/20315413/206762985-e0187904-e25e-4806-9098-0d2965407144.png)

**Comment by Dehelssey** [comment]
I tried the CSS background provided to help visually identify posts privacy level but i'm **not** convinced.
![feed](https://user-images.githubusercontent.com/20315413/213660727-31745622-9db4-48f7-aab3-114d1cd2e829.png)

pattern is either too strong and post less legible, or too light and not easily distinguishable from other patterns (especially for the curved and striped ones)

I think we should could use the icon only (which we **don't** have at the moment on our UI, except for followers-only and direct messages, at the place of the boost icon so not ideal)

Any thoughts on the background pattern @Cl0v1s ?

**Comment by Dehelssey** [comment]
![image](https://user-images.githubusercontent.com/20315413/213664924-14ef0949-6404-4370-9d34-e00a44d836e1.png)

previous export didn't show the actual background of Mangane so it kinda looked better^^

i chose a border for direct messages so that they pop out more, since the curved background pattern was the one that bothered me the most.

**Comment by Dehelssey** [comment]
(yes, spoilers on the sidebar as well^^)

**Comment by Dehelssey** [comment]
OK we're on the same page. Let's ditch the backgrounds.

I'll stick with the border on Direct Messages tho, if that's fine with you.

I tried a different icon for unlisted since the open lock felt a bit odd to me and too easily confusable with the locked one.

You make me realize we could also display the "local only" icon. 
BTW, are local-only posts actually public or unlisted ?

**Comment by Dehelssey** [comment]
![Section 1](https://user-images.githubusercontent.com/20315413/214174000-7ec839f8-c4eb-45df-b6a7-ee83decdc6f6.png)

**Comment by badrihippo** [comment]
On a related note, I notice there's no icon for local-only posts? Or am I missing something?

**Comment by Dehelssey** [comment]
You're right, for now all "public" states (ie "public", "unlisted" and "local-only") are displaying the same way.

We'll fix this in the future version of Mangane that @Cl0v1s is currently rewriting from scratch.
