### ISSUE TITLE
"Branding" Mangane

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#48]
Dans la continuité de ce que je disais dans #47 on pourrait ptet envisager un logo pour Mangane ? 

Concrètement je pense que, si Filip Toutou peut conserver sa place de mascotte, en concurrence avec le Mammouth de Masto et la pin up renard de Pleroma (wtf) il ne me parait pas trop adapté en logo.

On peut en revanche utiliser la grappe (qu'on retrouve d'ailleurs dans l'interface pour le fil "local", y'a le côté bordelais (en rappel au nom Mangane) et le côté social... On perd ptet la notion de voyou... Mais surtout on veut ptet garder la grappe spécifiquement pour Bdx.town ?

**Comment by Cl0v1s** [comment]
Je suis ouvert à cette idée, pour ma part la mascotte est un peu au second plan depuis qu'on a la grappe qui me semble bien plus indiquée pour l'instance. 

Mais on peut imaginer une variation de Fillip plus logoifié. Auquel cas je peux me rapprocher de Morgane à ce propos

**Comment by Dehelssey** [comment]
Ben l'idée c'est de séparer un peu le branding de Mangane de l'indentité de Bdx.town.
Histoire que les gens qui installent Mangane se retrouvent pas avec des grappes et des fils "Bdx.town" au lieu de "Local" par ex :D

**Comment by Cl0v1s** [comment]
Aujourd'hui c'est effectivement là le seul branding. 
Ce serait pas mal effectivement de rendre ça paramétrable depuis l'écran "mangane config". J'ai naivement directement importé le svg des grappes dans le code, mais j'aurai pu utiliser ce qui se trouve là

**Comment by Cl0v1s** [comment]
Ca perd aussi peut être moins les gens si, une fois installé, la webapp a le nom de leur instance et pas le nom du logiciel, non ?

**Comment by Dehelssey** [comment]
Ah oui, tant qu'ils ont pas de mention de bdx.town

**Comment by Dehelssey** [comment]
That doesn't solve the question of Mangane logo. 🤔 

Especially on fresh installs where admin don't change it (and the soapbox logo stays)

**Comment by Dehelssey** [comment]
I'll try and propose something cool for a Mangane logo.

for the record, "Mangane" is a word from Bordeaux, France, meaning "voyou" or, in english "rascal" or "thug".
I'd like to keep that imagery. → hence my first idea, a leather jacket.

We could also have a logo that somehow implies the ideas of social connection, local, sustainable design, leftist politics since they're part of our DNA...

**Comment by wakest** [comment]
@Dehelssey I looked through a bunch of jacket icons on TheNounProject and these were the best I found for inspiration:
https://thenounproject.com/icon/jacket-1464584/
https://thenounproject.com/icon/jacket-3690997/
https://thenounproject.com/icon/jacket-4795660/

**Comment by wakest** [comment]
this one also came up under related and is sorta good for "rascal" ![image](https://user-images.githubusercontent.com/7890201/213845097-feb0a360-18d3-42a5-b1a4-255b1434bedb.png)

**Comment by Cl0v1s** [comment]
The leather jacket ones are maybe a bit too complex to be used a logo ? 

The lighter one you provided is really cool tho ! 

Thanks a lot for your suggestions !
What do you think about that @Dehelssey ?

**Comment by Dehelssey** [comment]
i came to the same conclusion : leather jackets as a logo only works when it doesn't have to be used as an icon as well... like a biker crew logo or some vintage very detailed logos. Which is not really suitable for a digital use.

i like the lighter idea tho, since it can be declined for a responsive logo, like the full detailed lighter as big logo and just the flame when a smaller icon is needed.

i always enjoy a responsive logo so i'll try something there.

We've also discussed using an animal, like a racoon or a badger since they kinda look like thiefs or thugs already ^^ They can also be very stylized to be used as icons as you can see on examples i've gathered :
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/20315413/213993334-a6fb7fad-8363-46a0-81c6-ad9d3d619177.png">

**Comment by wakest** [comment]
have yall had any new thoughts about this? coming back to this I think the lighter would be a great logo and also could be reused in different ways like @Dehelssey was mentioning like using just the flame as a small version of the icon or animating the flame when the icon is bigger/more prominent.

**Comment by Dehelssey** [comment]
We havn't discussed this yet, @Cl0v1s also has a lot on his hands right now so a mangane branding is not the priority at all after all ^^

**Comment by Cl0v1s** [comment]
The new logo was added to the code, still have to show it somewhere in the UI (I believe your mokups are showing it on the right column on desktop)

**Comment by Dehelssey** [comment]
Yes, above the block of text where we talk about Mangane bring FOSS and proposing people to contribute

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/301
