### ISSUE TITLE
L'onboarding masque les statuts

### ISSUE THREAD

**Issue by Cl0v1s** [BDX-town/Mangane#59]
Lorsqu'on arrive sur l'interface d'un toot sans être connecté, l'onboarding masque les toots.

Eventuellement déplacer l'onboarding actuel pour le mettre dans l'onboarding par défaut de soapbox.

**Comment by Cl0v1s** [comment]
Tu penses quoi de l'intégrer dans l'onboarding de base @Dehelssey ? 

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/917518/201765750-b26fd82e-ab7e-4204-96eb-7564a6743f10.png">

Sinon en l'état les users se prennent deux onboarding de suite

**Comment by Dehelssey** [comment]
Oh j'ignorais qu'il y avait un onboarding de base.
Si je me crée un compte test je peux le voir ou c'est pas en prod ?

**Comment by Cl0v1s** [comment]
C'est en prod tu peux tester !

Le 14 novembre 2022 23:34:01 GMT+01:00, "Guérin" ***@***.***> a écrit :

**Comment by Cl0v1s** [comment]
Un avis sur la question ?

**Comment by Dehelssey** [comment]
j'ai fait un récap des différents écrans de l'onboarding natif et celui qu'on avait fait nous-mêmes et mes recos : 
https://arc.net/e/921F5416-1952-42DE-A9D3-B1A9343EAE05

**Comment by Cl0v1s** [comment]
Top merci beaucoup ! Je me penche là dessus ce week end ! 

Le 17 novembre 2022 14:19:30 GMT+01:00, "Guérin" ***@***.***> a écrit :
