### ISSUE TITLE
Better emojo selection UI

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#61]
Sur moobile 9 fois sur 10 l'écran de sélection d'emojis esr inutilisable,caché **sous** mon clavier tactile 

![Screenshot_20221112-164943_Vivaldi_Browser](https://user-images.githubusercontent.com/20315413/201482476-89af11d0-c951-44d1-8ccd-6ea9ff28da9d.png)

Sur l'app Mastodon, les emojis prennent la place du clavier tactile, c'est pas mal 
![Screenshot_20221112-155132_Mastodon](https://user-images.githubusercontent.com/20315413/201482506-2dbe415b-f92e-469e-b830-b45b9a968dfb.png)

En vrai c'est pareil sur pas mal d'apps, les emojis prennent la place du clavier. 

On perd l'option de recherche textuelle d'emoji, à voir comment on pourrait conserver les 2.

**Comment by Dehelssey** [comment]
Another option, maybe simpler to implement, would be that the emoji picker stays in the viewport, but sticked to the top of the screen.
That's what's done on mobile version of discord's webapp

![Screenshot_20221202-214848_Vivaldi_Browser](https://user-images.githubusercontent.com/20315413/205389039-d3c53207-effa-4cb0-9821-142bbf1c549d.png)

It could even taking all available space left by keyboard

**Comment by Cl0v1s** [comment]
I made it fullscreen + not focused the searchbox by default

**Comment by Cl0v1s** [comment]
(The component is still a mess, it will need a rework sooner or later)
