### ISSUE TITLE
Ability for users to **block** at instance level ?

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#68]
It feels like, right now, at the user scale we are only allowed to "mute" instances (the used word in UI is "hiding") and not a clear block...

Am i being mislead by that wording ? Or is block only an admin feature ?

If so it feels really important that users themselves have the ability to block entire domains as well as admins.

**Comment by Cl0v1s** [comment]
Block is an admin feature as it impacts all instance's users. 

technically block and mute are not equivalent. Block drops the data incoming from the blocked instance (so all users wont be able to see it). By muting, our instance receive the data and eventually show it to all the users except the ones whose used the mute option. 

When you block at user level it's the same: the instance drops the incoming data from the blocked user@instance to the blocker, so nobody on our instance can see it

**Comment by Dehelssey** [comment]
What i don't get then is why i can mute or block users but only mute instances 🤔

**Comment by Cl0v1s** [comment]
Mute -> you cant see activity of this user, others can

Block -> The server drops incoming activities involving this user and you

**Comment by Dehelssey** [comment]
Why is it possible for users on Mastodon to block an instance then ? 😔
