### ISSUE TITLE
UI major changes, at least on home page for non users

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#69]
At the moment, the home of any Mangane instance looks exactly like any Soapbox ones.

I tried my best not to judge software based on its founder, but it matters. Because most of its users share a view. An agenda. Which is cleary NOT something we want to be linked with.

Therefore, in order to differentiate us from them i strongly suggest we redesign at least the not-connected homepage.

We should also update our CoC (see #53) but that would only benefit Bdx.town while a redesign would benefit all instance owners using Mangane

**Comment by Cl0v1s** [comment]
I removed the milestone, since to embed it, I would like to have a mockup or something ready to code :)

Do you have any idea of what we could do?

**Comment by Dehelssey** [comment]
I have some ideas, i'll make you some propositions

**Comment by Cl0v1s** [comment]
I've asked people on the instance about what they expected before joining !

**Comment by Cl0v1s** [comment]
In order to show this content https://www.notion.so/guerin/Home-67c4b5fe04d04c80a55e095bcacfe1f7
We will need to make some modifications to the home page code. 

If you didnt have the time to think about it, we can for now: 

* Remove the weel known soapbox animation to differentiate from the army of shitholes instance 
* Add the moderating team
* Add the number of users 
* Add a space for the code

**Comment by Cl0v1s** [comment]
![image](https://user-images.githubusercontent.com/917518/204577987-b9629064-6449-4785-9a6c-55df4fe731d5.png)

**Comment by Dehelssey** [comment]
@Cl0v1s → même lien y'a une v2 desktop.

Je me demande si les admins on devrait pas les mettre dans le manifeste / comment ça marche ?

Remarque masto les affiche dès la home... 🤔

**Comment by Cl0v1s** [comment]
Ouais je pense c'est important de savoir à qui s'adresser sur le fediverse, ou par mail. Notamment pour ce qui concerne la modération (quand je vois une saloperie sur une instance pas dégeu, je passe par la pour savoir qui contacter)

**Comment by Dehelssey** [comment]
@Cl0v1s j'ai rebossé mes propales, voici donc la v3 🎉 

**Desktop view :** https://www.figma.com/proto/lOmoWp7cuw14qYPvZuoCFs/BDX.town---Design?page-id=538%3A523&node-id=574%3A214&viewport=-5862%2C-782%2C0.36&scaling=min-zoom

**Mobile view :** https://www.figma.com/proto/lOmoWp7cuw14qYPvZuoCFs/BDX.town---Design?page-id=7%3A241&node-id=576%3A661&viewport=-1081%2C-1139%2C0.83&scaling=scale-down

**Comment by bugsysop** [comment]
Sur une instance où les inscriptions ne sont pas ouvertes, l’appel à s’inscrire pour continuer la conversation est un peu troublant pour les visiteurs et visiteuses qui passent par là...

D’autant plus qu’ils et elles peuvent participer à la conversation en joignant n’importe quelle autre instance...

Peut-être rendre l’appel à inscription conditionnel, ou trouver une formulation plus générique sur la/le fédiverses.

![mangane-ui-1 ](https://user-images.githubusercontent.com/365281/208720468-d5879f1f-b6cc-403e-969f-c94f48198394.png)

**Comment by Dehelssey** [comment]
Ah oui effectivement je m'étais concentré sur la home j'avais pas fait attention qu'il y avait un bandeau sur les autres pages quand on est non-connecté.

En plus ce bandeau est bizarrement rédigé, puisqu'il part du principe que t'es nouveau mais tu peux quand même te co... 

@Cl0v1s j'hésite presque à le faire sauter carrément non ?

Est-ce qu'il est possible d'avoir un comportement différent selon si les inscriptions sont ouvertes ou pas ?

**Comment by bugsysop** [comment]
Oui le bandeau peut parfaitement être supprimé à mon avis... 

C’est assez invasif et dissuasif me semble-t-il. C’est aussi redondant avec le formulaire de login de la barre de navigationen haut de page

La mention en haut de colonne de droite devrait suffire éventuellement, mais en la rendant conditionnelle pour les cas d’inscriptions fermées

**Comment by Cl0v1s** [comment]
Oui, je suis partant pour le supprimer, ça fait très twiteresque comme truc, et pas vraiment dans le mood du fediverse

**Comment by Dehelssey** [comment]
C'est voté !

**Comment by Cl0v1s** [comment]
Je vais aussi retravailler un peu le menu latéral, pour nous permettre de plus simplement gérer les futurs ajouts, notamment de timeline

**Comment by bugsysop** [comment]
A ce propos, dans le menu de droite l’entrée « Importez vos données » c’est peut-être pas utile... On ne fait pas cela tous les jours. Un accès depuis les préférences suffit me semble-t-il

![mangane-export](https://user-images.githubusercontent.com/365281/209552920-70299741-1b72-45a9-8084-a8fb2470645f.png)

**Comment by Cl0v1s** [comment]
Pour le coup je suis pas convaincu que le mettre dans les paramètres soit souhaitable. Déjà que la notion de migration est pas facile à prendre en main s'il faut chercher dans l'interface pour trouver ce paramètres... 

Un avis UX sur la question à @Dehelssey ? Personnellement je serai pour demander aux personnes ayant utilisé la fonction leur retour d'expérience :)

**Comment by Cl0v1s** [comment]
En revanche, il va falloir peut être créer un écran "données" pour ces questions, donc effectivement à voir pour lien avec la https://github.com/BDX-town/Mangane/issues/118

**Comment by bugsysop** [comment]
Ici, dans le autres paramètres, cela me semble assez visible d'ajouter une entrée Importer/exporter

![settings-1](https://user-images.githubusercontent.com/365281/209572731-2f44e27e-da02-41d2-9178-9751a916f633.png)

**Comment by Dehelssey** [comment]
## Home 
![home2023](https://user-images.githubusercontent.com/20315413/214177411-5d9bf8c5-eb18-4fe3-a8cb-0b6d03a42380.png)

## Feed
![mac](https://user-images.githubusercontent.com/20315413/214177413-d722b7e4-82e1-4379-95b2-e93ddf9f6eaa.png)
