### ISSUE TITLE
Change search tabs order and fix selected tab when making a new search

### ISSUE THREAD

**Issue by ymollard** [BDX-town/Mangane#70]
Lorsqu'on colle une URL dans le moteur de recherche (URL vers un compte Masto ou vers un pouet) l'adresse du compte/pouet recherché n'est pas chargée et on obtient des résultats non pertinents.

C'est une fonctionnalité intéressante pour ceux qui ont plusieurs comptes sur plusieurs instances, ça permet de booster sur un compte B un pouet qu'on a vu sur un compte A, idem pour le follow.

Je ne sais pas quel est le degré d'implémentabilité de cette feature ?

**Comment by Dehelssey** [comment]
Heu... je veux bien un exemple de lien qui ne marche pas, je n'ai jamais eu ce problème...
 
Je viens encore de tester au hasard 
![Screenshot_20221120-004503_Vivaldi_Browser](https://user-images.githubusercontent.com/20315413/202875966-ebbc114f-cc87-4ef1-a431-03ac6624e65c.png)
![Screenshot_20221120-004452_Vivaldi_Browser](https://user-images.githubusercontent.com/20315413/202875969-a1bbbb8e-6424-4e91-bd27-88708a5451e2.png)

Par défaut la recherche se fait dans compte et non statut faut manuellement choisir le bon type d'objet recherché...

**Comment by ymollard** [comment]
Ha oui pardon, c'est moi, il faut cliquer sur **Statuts**. Cependant est-ce que ça ne pourrait pas être fait automatiquement ? 
Si on cherche un lien vers un statut ça me parait pas idiot d'activer la recherche par statut.

Pour la recherche par URL de comptes, je n'arrive plus à reproduire de souci en effet. Désolé on peut fermer et je ferai un suivi si je trouve une URL qui ne charge pas.

**Comment by Cl0v1s** [comment]
La recherche est un peu cassée en l'état, si on fait: 

1. Recherche 
2. Change onglet 
3. Recherche

On reste sur l'onglet du 2 alors que les données affichées sont toujours à nouveau des comptes. 
On peut fixer ça sur cette release + mettre les status en premier

**Comment by ymollard** [comment]
> Pour la recherche par URL de comptes, je n'arrive plus à reproduire de souci en effet.

J'ai réussi à reproduire le problème aujourd'hui : 
en cherchant un compte via son URL ce midi je n'obtenais aucun résultat pertient, par contre en cherchant le handle @user@instance j'avais bien le bon résultat en tête de liste.

Je viens de retester ce soir après avoir laissé passer quelques heures et cette fois-ci j'ai le compte pertient qui ressort même avec la recherche par URL. J'ai l'impression qu'il a fallu quelques heures à la recherche par URL pour finir par remonter de bons résultats et que la recherche par handle fonctionne, elle, immédiatement.  

De plus (c'est pas vraiment lié à cette issue 70 mais jsp trop), j'ai un compte suivi pour lequel ses pouets ne se chargent pas, alors que ça fait déjà plusieurs heures que je le suis (et qu'il a bel et bien des pouets) :
![image](https://user-images.githubusercontent.com/3295098/208265637-72c95820-abeb-47f5-b9b5-c2531a187f16.png)

**Comment by Cl0v1s** [comment]
Alors pour la question des Statuts "manquants", ça c'est normal, et si je ne m'abuse, c'est comme ça que le fediverse fonctionne. 

Ne vont apparaître les statuts qu'une fois qu'au moins 1 personne de l'instance ai déjà suivi la personne en question. La récupération des statuts n'est pas rétro-active.

Pour ce qui est de la recherche, les gars d'Akkoma ont plusieurs fois signifié que la recherche native de pleroma était naze, et ont donc ajouté un support pour elasticSearch. Je peux essayer de l'activer sur l'instance :)
