### ISSUE TITLE
Boosted posts with CW are always open

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#74]
For a few weeks (monthes?) i was under the impression that CW behaviour was kinda erratic on my timelines. 

Posts with CW were mostly closed (as they should) but some posts were open by default. 

Moreover, i realized i couldn't even close them when clicking the fold/unfold button.

Tonight i think i figured the reason : only **boosted** post with CWs are open. Regular posts with CWs are closed.

Why whould boosts override CWs fold/unfold feature ? 🤷

**Comment by Cl0v1s** [comment]
I noticed the same issue on my own TL. I'll check that.

**Comment by Cl0v1s** [comment]
Reproduced. I fix it.

**Comment by Dehelssey** [comment]
Wow, so quick ! Thanks !
