### ISSUE TITLE
Provide a way to mask the Discovery button on the left menu

### ISSUE THREAD

**Issue by mlcdf** [BDX-town/Mangane#79]
That discovery button (for the global timeline view) on the left menu is the gateway to The Bottomless Vortex of Stuff.

I'd love a way to mask the button! :)

**Comment by Cl0v1s** [comment]
So you would like to have an option from your settings to edit the layout of this menu ? :)

**Comment by mlcdf** [comment]
I would :)

**Comment by Dehelssey** [comment]
Display:none 😅

**Comment by mlcdf** [comment]
Fixed with the new discovery button
