### ISSUE TITLE
Translate sensitive media description and edit menu entry / feedback

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#81]
Right now the "sensitive media" modal only has its title in french. Both description and button are in english no matter what.

![image](https://user-images.githubusercontent.com/20315413/204226254-40a9a900-7be5-43ac-ac40-8f92929abe60.png)

proposition de traduction :
> **Contenu sensible**
> Ce media a été marqué comme ne convenant pas à tout public
> 👁️ Afficher le media

**Comment by Cl0v1s** [comment]
The edit feature is also not translated at this point, i'll do both.
