### ISSUE TITLE
Missing translation "Never" in profile directory

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#88]
In the directory, we have the "last activity" field that help users see if a user is dormant.

When last activity is X days ago, the X number isn't displayed at all 

![Screenshot_20221202-170337_Vivaldi_Browser](https://user-images.githubusercontent.com/20315413/205336102-574e07a3-3c2f-40f0-9f81-695fa9962bde.png)

**Comment by Dehelssey** [comment]
okay... seems like it's already fixed ? 🤔

**Comment by Cl0v1s** [comment]
Non reproduis, je sais pas à quoi c'est dû 

![image](https://user-images.githubusercontent.com/917518/206748897-5a840d33-d7cf-402a-a40b-67125ecb247b.png)

**Comment by Dehelssey** [comment]
Seems like it only happens for "1" Jours. Didn't make the screen last time and now i can't find any profile that has been active 1 day ago ^^
