### ISSUE TITLE
Add custom reactions

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#91]
Allow people to interact with posts with whatever emoji they want, custom or classic.

I believe Akkoma already supports custom reactions, not sure how much work it implies to make Mangane recognize/diwplay the feature tho.

Anyhow, i still would have to design the new modal to select said custom reaction. (or used the same one as for inserting emojos in posts)... Meaning we should find a similar solution both for this issue and for #61

**Comment by Cl0v1s** [comment]
For now I already a support for displaying foreign custom reactions, but it adds solid basis to allow or own users to react with our own emojos

**Comment by Cl0v1s** [comment]
fixed in https://github.com/BDX-town/Mangane/pull/280
