### ISSUE TITLE
Change responsive breakpoints

### ISSUE THREAD

**Issue by Dehelssey** [BDX-town/Mangane#92]
Right now, based on the CSS, the right sidebar only appears on "xl" screens.
when we hit "lg" range of screens, it disappears and the feed takes the remaining place.

Therefore on the macbook i'm stuck with a way too large column and no sidebar :(

We can very simply fix this with some classes changes. I tried with success in the inspector.

## Fix

replace 
`<main class="md:col-span-12 lg:col-span-9 xl:col-span-6 pb-36 pt-3 sm:pt-0 dark:divide-slate-800 space-y-3">` 
by
`<main class="md:col-span-12 lg:col-span-6 xl:col-span-6 pb-36 pt-3 sm:pt-0 dark:divide-slate-800 space-y-3">`

and the following sibling element 
`<class="hidden xl:block xl:col-span-3">` 
by 
`<aside class="hidden lg:block lg:col-span-3">`

before
![image](https://user-images.githubusercontent.com/20315413/205451431-16afdb04-bcd4-491e-8e84-b78a43d83d75.png)

after
![image](https://user-images.githubusercontent.com/20315413/205451493-92637a90-3cc1-4cad-a066-5f629d7a4fb6.png)

**Comment by Dehelssey** [comment]
I'm not sure how to fix this directly in the code and ask for a merge request so... there it is^^

**Comment by Cl0v1s** [comment]
I guess it's that commit ? :P
feaa44fda7c10145925b4ccb39473b7113002989

**Comment by Dehelssey** [comment]
yes ? 👀

i just wanted to be a "real" contributor^^

**Comment by Cl0v1s** [comment]
Already merged.
