### ISSUE TITLE
Akkoma bubble timeline

### ISSUE THREAD

**Issue by gerwitz** [BDX-town/Mangane#93]
I would like to view the Akkoma "bubble" timeline, which is visible in Pleroma FE but I cannot find with Mangane.

**Comment by Dehelssey** [comment]
What is the "bubble" timeline ? I know of home / local / federated (which are home / %instance_name% / Discover in Mangane) but i don't know the bubble one... Can you provide a screenshot of what you're talking about ? or at least what's supposed to be displayed in that timeline ?

**Comment by Cl0v1s** [comment]
The bubble timeline is a special feature on Akkoma allowing the admin the select by hand a few set of remote "siblings" instances. 
Mangane will support it, but I think we may need to rethink the navigation. Especially on mobile were the left panel is starting to be a bit messy.

Le 8 décembre 2022 11:29:21 GMT+01:00, "Guérin" ***@***.***> a écrit :

**Comment by Dehelssey** [comment]
ooooh, nice ! i didn't find info about it on akkoma.social but that's a nice feature indeed. Looking forward to work on it !

indeed, we start to have many options in that left menu... And no more room in the bottom bar... 

i'll add this to my to-do !

**Comment by deltatux** [comment]
> The bubble timeline is a special feature on Akkoma allowing the admin the select by hand a few set of remote "siblings" instances. Mangane will support it, but I think we may need to rethink the navigation. Especially on mobile were the left panel is starting to be a bit messy. Le 8 décembre 2022 11:29:21 GMT+01:00, "Guérin" ***@***.***> a écrit :
> […](#)
> What is the "bubble" timeline ? I know of home / local / federated (which are home / %instance_name% / Discover in Mangane) but i don't know the bubble one... Can you provide a screenshot of what you're talking about ? or at least what's supposed to be displayed in that timeline ? -- Reply to this email directly or view it on GitHub: [#93 (comment)](https://github.com/BDX-town/Mangane/issues/93#issuecomment-1342488698) You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

+1 on getting Bubble Instance support.

As for the mobile navigation issue, maybe hide it into a Timeline button and then make the timeline selection as a dropdown? I know some mobile apps tackle this issue like this. I think it makes sense instead of each timeline get their own buttons on the bottom nav bar.

**Comment by Cl0v1s** [comment]
With Mangane keep the last selected option in the user's settings. It's indeed a good alternative. 

Any thoughts on that @Dehelssey ?

**Comment by Cl0v1s** [comment]
What do you think of something like this ? 

Desktop: 
<img width="1434" alt="Capture d’écran 2022-12-26 à 17 55 42" src="https://user-images.githubusercontent.com/917518/209569574-c82af5b8-7e9e-46cd-af0b-91f4795e739f.png">

Mobile:
<img width="360" alt="Capture d’écran 2022-12-26 à 17 56 18" src="https://user-images.githubusercontent.com/917518/209569579-f08988ca-adbd-45ab-af85-d4b880aeec87.png">

This way we do not complexify the overall navigation, and we keep our current logic: the "discover" section is there to help discover new people, just has the whole bubble feature

**Comment by gerwitz** [comment]
I may be an outlier because I run a personal instance, but I would prefer to switch my *local* timeline with the bubble.

**Comment by Cl0v1s** [comment]
We can't really do that for all the configurations.
Are you using the single user mode of mangane ? 

Le 26 décembre 2022 20:56:31 GMT+01:00, Hans Gerwitz ***@***.***> a écrit :

**Comment by deltatux** [comment]
I really like the mock-up, looks great but like @gerwitz, I too run a single user instance where the local timeline is quite useless. 

Is there a way to make it an option to hide it in the settings if possible or collapse the local timeline button into the Discover button as well?

**Comment by Cl0v1s** [comment]
If you are both using mangane in single user mode (visible in the mangane settings), yes, I should be able to replace the local timeline with the bubble one only in single user mode. That, while keeping it accessible for multi-users instances ! 

I have all the code ready already, I just need to see what @Dehelssey thinks of the tab idea :)

**Comment by deltatux** [comment]
> If you are both using mangane in single user mode (visible in the mangane settings), yes, I should be able to replace the local timeline with the bubble one only in single user mode. That, while keeping it accessible for multi-users instances !
> 
> I have all the code ready already, I just need to see what @Dehelssey thinks of the tab idea :)

Is there a way to have a separate settings toggle for it as well? I generally don't use single user mode so only those who purposely navigate to my profile or interact with me can see what I post instead of it being on the front page (just a preference thing). Thanks!

**Comment by gerwitz** [comment]
I currently use the "homepage is my profile" mode but would also prefer a separate toggle. (I am the only human on my instance, but I tend to experiment with multiple accounts on it.)

**Comment by Cl0v1s** [comment]
After a bit of thinking, I agree with you that this feature should be optional. 
Moreover some of our users think that the federated timeline is a bit useless (especially on big instances, where you can find a lot of Nazi crap in it). 

It would allow us to address both issues with making a option to replace the federated timeline with the bubble one, creating a more curated experience (which I think is more in line with this project objectives). 

We would avoid a lot of ux issues too.

Le 27 décembre 2022 18:38:28 GMT+01:00, Hans Gerwitz ***@***.***> a écrit :

**Comment by Cl0v1s** [comment]
Here is a possible result: 

Desktop:  
![image](https://user-images.githubusercontent.com/917518/209734785-b4bbdc83-5472-4aaa-bef3-bb97865d9b7c.png)

Mobile:  
![image](https://user-images.githubusercontent.com/917518/209734807-be946afa-4fb9-4de2-8ddc-9e8366c7de34.png)

Settings:  
![image](https://user-images.githubusercontent.com/917518/209734851-36df2bfc-d652-4148-9e6c-45debe188bbd.png)

Any thoughts ?

**Comment by deltatux** [comment]
> 

Sorry my French isn't that good, in the photo, the toggle asks if you wanted to replace the federated timeline with the bubble timeline?

Could there be a way to select what timeline to replace? For me the Bubble & Federated timeline are more useful than the Local Timeline for a single user instance but I understand why for a large instance the Federated timeline is useless.

The way that the Husky app I think does it best, it allows for a lot of customization but I know this won't be easy to implement in a web app, but it's food for thought. It allows you to choose which timeline makes sense for your use case. By default the Bubble Timeline is hidden but for me, I actually add it and then remove the Local timeline as that's useless for me but for someone else they can have the Local and Bubble timeline and remove the federated one.

![Screenshot_20221227-204924](https://user-images.githubusercontent.com/59618028/209744885-114fa203-a8af-4b05-a201-c2799a71e3dc.png)

Another option I'm thinking is, one can have the Discover button and then within the Discover button, have a dropdown menu where the "What is the Fediverse?" banner is located now, this menu would allow you to choose Local, Bubble or Federated and let the user decide that way? Or when you press the Discover button, a pop up with the option occurs? (Though the last one I don't know how good of a UX design that is as I'm not a UX designer).

**Comment by Cl0v1s** [comment]
User customization is indeed the best solution for this issue. However it would require a huge rework of the overall navigation and the way the app behave in general and cannot be addressed in the current issue alone as it required an important rethinking of the app.

For now, we have to try to make this timeline accessible in the current navigation which expose a bit of an UX issue as adding simply *another* timeline (and so navigation entry etc..) would confuse the average user (we all seem to be "power users" here, but a rather accessible interface is what's making this UI interesting).

For now, what will be done is the following as you seem to still need the global fediverse timeline: 
* Bubble timeline can be activated from the Mangane settings 
* If activated, the discover timeline now exposes a toggle to switch from "curated mode" (bubble timeline) to "uncurated mode" (classical public timeline). This settings is saved in the user's setting

**Comment by Cl0v1s** [comment]
Some of our users at bdx.town already requested the customization feature you are describing (originally to remove the public timeline from their UI). It seems to be a reccuring concern. Maybe we could create a separate issue to address the overall problem ?

**Comment by Cl0v1s** [comment]
So the setting was moved from per instances to per user: 
![image](https://user-images.githubusercontent.com/917518/209819496-9ae74520-ccd9-4dbd-87ea-a288b29f5085.png)

It's activated by default if the instance is running on Akkoma

**Comment by deltatux** [comment]
> Some of our users at bdx.town already requested the customization feature you are describing (originally to remove the public timeline from their UI). It seems to be a reccuring concern. Maybe we could create a separate issue to address the overall problem ?

Definitely can be tackled down the road in another ticket. I think for this milestone, it's best to keep it as is and then rethink it down the road! Thanks for all the hard work!
