### ISSUE TITLE
Clicking Add removes the previous item added in the promo panel. 

### ISSUE THREAD

**Issue by jsailo** [BDX-town/Mangane#98]
1. I enter the label and UR, click Click + Add. It just disappears. 
2. Refresh the page, the promo panel appears to have been added to the right hand side panel. 
3. Try to add another one, the previous one is removed. 

Adding behavior in Soapbox for comparison (can't help it). The behavior for Mangane **starts at 0:11** of the video.
EDIT: I'm on vgoodcook-raccoon-b4be495 BTW.

https://user-images.githubusercontent.com/35369823/207369306-46558257-e655-4249-b5f5-f667ddb1bdc6.mp4

**Comment by Dehelssey** [comment]
Looks like #95 to me

**Comment by Cl0v1s** [comment]
Thanks for your feedback, it's indeed a duplicate and will be fixed on next release :)
